#!/bin/bash -e
if [[ ! -f "/home/spark-139b9f46-c3ad-4342-b1f0-77/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-139b9f46-c3ad-4342-b1f0-77/tmp/uv/uv_0.6.10_linux_amd64" "$@"
